---
version: '2'
services:
  # Can't use service elasticsearch=<num> for now due to named volumes
  elasticsearch1:
  # Equivalent to:
  # docker run --rm --cap-add=IPC_LOCK --ulimit memlock=-1:-1 --ulimit nofile=65536:65536 -t -P --memory="4g" -e "discovery.zen.minimum_master_nodes=${ES_NODE_COUNT}" -v esdata:/usr/share/elasticsearch/data docker.elastic.co/elasticsearch/elasticsearch:5.0.0-rc1
    build:
      context: build/elasticsearch
      dockerfile: Dockerfile
      args:
        ELASTIC_VERSION: "${ELASTIC_VERSION}"
        ES_DOWNLOAD_URL_PREFIX: "${ES_DOWNLOAD_URL_PREFIX}"
        ES_JAVA_OPTS: "${ES_JAVA_OPTS}"
    cap_add:
      - IPC_LOCK
    command: "bin/elasticsearch -E discovery.zen.minimum_master_nodes=$${ES_NODE_COUNT:-1}"
    image: "elasticsearch:${ELASTIC_VERSION}"
    mem_limit: 2g
    ports:
      - 9200:9200
      - 9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - esdata1:/usr/share/elasticsearch/data
  elasticsearch2:
    build:
      context: build/elasticsearch
      dockerfile: Dockerfile
      args:
        ELASTIC_VERSION: "${ELASTIC_VERSION}"
        ES_DOWNLOAD_URL_PREFIX: "${ES_DOWNLOAD_URL_PREFIX}"
        ES_JAVA_OPTS: "${ES_JAVA_OPTS}"
    cap_add:
      - IPC_LOCK
    command: "bin/elasticsearch -E discovery.zen.ping.unicast.hosts=elasticsearch1 -E discovery.zen.minimum_master_nodes=$${ES_NODE_COUNT:-1}"
    image: "elasticsearch:${ELASTIC_VERSION}"
    links:
      - elasticsearch1
    mem_limit: 2g
    ports:
      - 9200
      - 9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - esdata2:/usr/share/elasticsearch/data
  tester:
    build:
      context: build/python
    command: py.test -p no:cacheprovider tests/test_xpack_basic_index_crud.py
    image: "tester:latest"
    links:
      - elasticsearch1:elasticsearch
    volumes:
      - $PWD/tests:/home/testuser/tests:ro
volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
